export const modalConfigs = {
  delete: {
    icon: "trash",
    iconColor: "text-red-100",
    iconSize: 36,
    title: "일정을 삭제하시겠습니까?",
    description: "삭제한 일정은 다시 되돌릴 수 없습니다.",
    warning: "*하위 할 일을 포함한 모든 데이터가 함께 삭제됩니다.",
    info: null,
    buttonCancelText: "취소",
    buttonConfirmText: "삭제",
    buttonDisabled: false,
    confirmVariant: "warning" as const,
  },
  progress: {
    icon: "trash",
    iconColor: "text-red-100",
    iconSize: 36,
    title: "카드를 삭제하고 있습니다.",
    description: "잠시만 기다려주세요.",
    warning: null,
    info: null,
    buttonCancelText: "취소",
    buttonConfirmText: "삭제중",
    buttonDisabled: true,
    confirmVariant: "warning" as const,
  },
  success: {
    icon: "circleCheckFilled",
    iconBgColor: "bg-green-50",
    iconColor: "text-green-500",
    iconSize: 45,
    title: "일정 삭제가 완료되었습니다.",
    description:
      "모든 하위 작업이 삭제되었습니다.<br/>대시보드가 업데이트 되었습니다.",
    warning: null,
    info: "*5초 뒤, 아무런 동작이 없을 시 자동으로 창이 닫힙니다.",
    infoColor: "text-gray-400",
    buttonCancelText: null,
    buttonConfirmText: null,
    buttonDisabled: false,
  },
  error: {
    icon: "alertTriangle",
    iconBgColor: "bg-red-50",
    iconColor: "text-red-500",
    iconSize: 36,
    title: "삭제에 실패했습니다.",
    description: "재시도 해주세요.",
    warning: null,
    info: null,
    buttonCancelText: "취소",
    buttonConfirmText: "재시도",
    buttonDisabled: false,
    confirmVariant: "warning" as const,
  },
};
