import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import Provider from "@/providers/providers";
import { Navigation } from "@/components/layout/Navigation";
import Toaster from "@/components/ui/Toaster";
import AuthProviders from "@/providers/AuthProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full overflow-hidden bg-white dark:bg-black text-gray-900 dark:text-gray-100`}
        suppressHydrationWarning={true}
      >
        <Provider>
          <AuthProviders>
            <div className="h-full flex flex-col dark:dark:bg-black">
              <Header />

              <div className="flex-1 overflow-hidden">{children}</div>

              <Toaster />
            </div>
          </AuthProviders>
        </Provider>
      </body>
    </html>
  );
}
